name: backend
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.16"]
      fail-fast: true
    # env:
    #   GO111MODULE: "on"
    #   RUNNER_TEMP: "/tmp/"
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get update && sudo apt-get install -y git gcc
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ matrix.go }}
      - run: go get -u github.com/swaggo/swag/cmd/swag@1.6.7
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: swag init -o ./doc/ -g swagger.go -d ./pkg/api/
      - run: go build
